carts/urls.py
from .views import *
from . import views
from django.urls import path , include

urlpatterns = [ 
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    # path('delete_cart/<int:cart_id>', CartDeleteView.as_view(), name='cart_delete'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home' ),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('online/', TemplateView.as_view(template_name='online.html'),name='online'),
    path('teacher/', TemplateView.as_view(template_name='teacher.html'),name='teacher'),
    path('about/', TemplateView.as_view(template_name='about.html'),name='about'),
    path('contact/', TemplateView.as_view(template_name='contact.html'),name='contact'),

    # admin panel
    # product
    path('panel/', TemplateView.as_view(template_name='./panel/panel.html'),
    name='panel'),
    path('panel/product/',ProductListViewAdmin.as_view(),name='product_view_admin'),
    path('panel/product/new/', ProductCreateView.as_view(), name='product_create'),
    path('panel/product/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('panel/product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    #category
    path('panel/category/',CategoryListView.as_view(),name='category_view'),
    path('panel/category/new/', CategoryCreateView.as_view(), name='category_create'),
    path('panel/category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('panel/category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),

    ##city
    path('panel/city/',CityListView.as_view(),name='city_view'),
    path('panel/city/new/', CityCreateView.as_view(), name='city_create'),
    path('panel/city/<int:pk>/', CityDetailView.as_view(), name='city_detail'),
    path('panel/city/<int:pk>/edit/', CityUpdateView.as_view(), name='city_update'), 
    path('panel/city/<int:pk>/delete/', CityDeleteView.as_view(), name='city_delete'),

    ##Teacher
    path('panel/Teacher/',TeacherListView.as_view(),name='Teacher_view'),
    path('panel/Teacher/new/', TeacherCreateView.as_view(), name='Teacher_create'),
    path('panel/Teacher/<int:pk>/', TeacherDetailView.as_view(), name='Teacher_detail'),
    path('panel/Teacher/<int:pk>/edit/', TeacherUpdateView.as_view(), name='Teacher_update'), 
    path('panel/Teacher/<int:pk>/delete/', TeacherDeleteView.as_view(), name='Teacher_delete'),

    #stock
    path('panel/stock/',StockListView.as_view(),name='stock_view'),
    path('panel/stock/new/', StockCreateView.as_view(), name='stock_create'),
    path('panel/stock/<int:pk>/', StockDetailView.as_view(), name='stock_detail'),
    path('panel/stock/<int:pk>/edit/', StockUpdateView.as_view(), name='stock_update'), 
    path('panel/stock/<int:pk>/delete/', StockDeleteView.as_view(), name='stock_delete'),
    

    path('ComingSoon/', TemplateView.as_view(template_name='ComingSoon.html'),name='ComingSoon'),
    path('Album/', TemplateView.as_view(template_name='album.html'),name='album'),
    path('store/', include('store.urls')),
     path('', include('accounts.urls')),
    path('cart/', include('carts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category
from teacher.models import Teacher

# Create your models here.

class Product(models.Model):
    product_name = models.CharField((" نام محصول "),max_length=2000, unique=True)
    slug = models.SlugField(max_length=2000, unique=True)
    description = models.IntegerField((" مدت زمان دوره"), blank=True, help_text=" ساعت ")
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    date = models.TextField((" تاریخ دوره "),max_length=200,blank=True)
    reg_date = models.TextField((" مهلت ثبت نام "),max_length=200,blank=True)
    full_description = models.TextField((" توضیحات "),max_length=20000, blank=True)
    price = models.IntegerField((" قیمت "),help_text=" تومان ")
    images = models.ImageField((" تصویر "),upload_to='photos/product')
    stock = models.IntegerField((" ظرفیت "))
    is_available = models.BooleanField((" فعال "),default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField((" تاریخ ایجاد "),auto_now_add=True)
    modified_date = models.DateTimeField((" تاریخ آخرین تغیر "),auto_now=True)
    

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class StockProduct(models.Model):
        name = models.ForeignKey(Product, on_delete=models.CASCADE)
        Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
        quantity = models.PositiveIntegerField((" ظرفیت "),default=20) 

        def __str__(self):
          return f'{self.name} {self.Teacher}'

templates/panel/product/product_create.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>

</head>


<br><br>
<div class="update-view-container">
  <h2 class="update-title">ایجاد محصول جدید</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'product_view_admin' %}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-submit">ثبت</button>
    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/product/product_delete.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>

</head>


<br><br>
<div class="update-view-container">
  <h2 class="update-title">حذف {{ object }}</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <p>آیا می خواهید محصول زیر را حذف کنید؟</p><br>
    <strong>"{{ product.product_name }}"</strong>
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'product_view_admin'%}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-delete">حذف</button>
    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/product/product_detail_admin.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}
    
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{ single_product.images.url }}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
    <article class="content-body">
    
    <h2 class="title" style="color: black;text-align:center;">{{ single_product.product_name }}</h2>
    <hr>
    <div class="mb-3"> 
      <p style="color: black;text-align:right;"><b>مدت زمان: </b> {{ single_product.description  }}</p>
      <p style="color: black;text-align:right;"><b>تاریخ: </b> {{ single_product.date }}</p>
      <p style="color: black;text-align:right;"><b>مدرس: </b> {{ single_product.teacher }}</p>
      <div class="price mt-1"> <p style="color:black;text-align:right;"><b>هزینه: </b>{{ single_product.price }} تومان</div> <!-- price-wrap.// -->
    </div> 
        <hr>
        <div class="mb-3"> 
          <p style="color: black;text-align:center;"><b>ظرفیت دوره: </b> <span style="color: blue">{{ single_product.stock  }}
          <p style="color: black;text-align:center;"><b>ظرفیت باقی مانده: </b> <span style="color: green">{{ single_product.stock }}
          <p style="color: black;text-align:center;"><b>زمان ثبت نام: </b> <span style="color: red">{{ single_product.reg_date }}</p>
        </div> 
        <hr>
        {% if single_product.stock <= 0 %}
        <button class="btn  btn-secondary" disabled> <span class="text" color="white" >ظرفیت تکمیل است</span> </button>
          
        {% else %}
          {% comment %} <a href="{% url 'add_cart' single_product.id %}" class="btn  btn-primary"> <span class="text">ثبت نام</span> <i class="fas fa-shopping-cart"></i>  </a> {% endcomment %}
        
        {% endif %}
        
      </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    <br>
    <section style="background-color:	#f0f0f0"> 
	
			<div class="container" style="background-color: white;">
        <h2 style="text-align:right;color:#c10000;">:توضیحات</h2>
        <p style="color: black;text-align:right;font-size:18px;"><b>{{ single_product.full_description  }}</b></p>
    </section>
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3 style="text-align:right">نظرات </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static './images/avatars/avatar2.jpg' %}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">1402.02.30 </span>  
                    <h6 class="mb-1">علی سعادت وند </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <b><p style="text-align:right;font-size:14px;">
                    ممنون دوره خیلی خوب و مفیدی بود. حتما این دوره رو به بقیه دوستان معرفی خواهم کرد و لطفا اگر میشه دوره های بیشتری
                    در همین زمینه برگزار کنید که بتونه یک چشم انداز مفید برای ما ایجاد کنه 
                </p></b>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/panel/product/product_update.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>

</head>


<br><br>
<div class="update-view-container">
  <h2 class="update-title">ویرایش {{ object }}</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'product_view_admin' %}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-submit">ویرایش</button>
    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/product/product_view_admin.html
{% extends 'baseadmin.html' %}
{% load static %}

{% block content %}

    <!-- ========================= SECTION INTRO END// ========================= -->
<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm"
		style="
			background: #f0f0f0
		"
>
<div class="container">

<header class="section-heading">
    <style>
        .dena{
            text-decoration:none;
            display: block;
              width: 40%;
              height: 40px;
              background-color:#EF4056 ;
              text-align: center;
              border-radius: 8px;
              color: whitesmoke;
              margin-top: 20px;
              margin-bottom: 20px;
              font-family: yekan;
              font-size: 20px;
              transition: 300ms;
          }
          .dena:hover{
              color: #2b2b2b;
              background-color:#e8102d ;
          }
    </style>
    <div align="center">
        <a href="{% url 'product_create' %}" class="dena"> اضافه کردن دوره جدید</a>
        <a href="{% url 'panel' %}" class="dena"> صفحه اصلی پنل</a>
        <a href="{% url 'home' %}" class="dena">خروج از پنل</a>
        
	    
    </div>

	
<div class="row">
	{% for product in product_list %}
	<div class="col-md-3">
		<div class="card card-product-grid">
			<a href="{{ product.get_url }}" class="img-wrap"> <img src="{{ product.images.url }}"> </a>
			<figcaption class="info-wrap">
				<a href="{{ product.get_url }}" class="title">	<b><p style="color: black;text-align:center;">{{ product.product_name }}</b></p></a>
				<hr><br>
				<p style="color: black;text-align:right;"><b>مدت زمان:</b> {{ product.description }}</p>
				<p style="color: black;text-align:right;"><b>تاریخ:</b> {{ product.date }}</p>
				<p style="color: black;text-align:right;"><b>مدرس:</b> {{ product.teacher }}</p>
				<p style="color:red;text-align:right;"><b>نوع آموزش:</b> {{ product.category.category_name }}</p>
				<div class="price mt-1">{{ product.price }} تومان</div> <!-- price-wrap.// -->
				<br>
				{% if user.is_authenticated %}
				<div style="background-color:#0b8ac8;width:100%;height:150px;
				text-align:center;border-radius:0 0 10px 10px;padding-top:6px;
				float:right;libe-height:20px !important;">
				<a href="{{ product.get_url }}" class="doreh-btn-more-full"><p style="color:white"><b>جزئیات محصول </b></p>
				</a>
                <hr width="50%">
                <a href="{% url 'product_update' product.pk %}" class="doreh-btn-more-full"><b style="color:yellow">  ویرایش محصول </b></a>
                <hr width="50%">
                <a href="{% url 'product_delete' product.pk %}" class="doreh-btn-more-full"><b style="color:red"> حذف محصول </b></a>
			    </div>
				{% endif %}
			</figcaption>
		</div>
	</div> <!-- col.// -->
	{% endfor %}
</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// 



</section>
</body>
</html>

{% endblock %}