carts/urls.py
from .views import *
from . import views
from django.urls import path , include

urlpatterns = [ 
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    # path('delete_cart/<int:cart_id>', CartDeleteView.as_view(), name='cart_delete'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home' ),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('online/', TemplateView.as_view(template_name='online.html'),name='online'),
    path('teacher/', TemplateView.as_view(template_name='teacher.html'),name='teacher'),
    path('about/', TemplateView.as_view(template_name='about.html'),name='about'),
    path('contact/', TemplateView.as_view(template_name='contact.html'),name='contact'),

    # admin panel
    # product
    path('panel/', TemplateView.as_view(template_name='./panel/panel.html'),
    name='panel'),
    path('panel/product/',ProductListViewAdmin.as_view(),name='product_view_admin'),
    path('panel/product/new/', ProductCreateView.as_view(), name='product_create'),
    path('panel/product/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('panel/product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    #category
    path('panel/category/',CategoryListView.as_view(),name='category_view'),
    path('panel/category/new/', CategoryCreateView.as_view(), name='category_create'),
    path('panel/category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('panel/category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),

    ##city
    path('panel/city/',CityListView.as_view(),name='city_view'),
    path('panel/city/new/', CityCreateView.as_view(), name='city_create'),
    path('panel/city/<int:pk>/', CityDetailView.as_view(), name='city_detail'),
    path('panel/city/<int:pk>/edit/', CityUpdateView.as_view(), name='city_update'), 
    path('panel/city/<int:pk>/delete/', CityDeleteView.as_view(), name='city_delete'),

    ##Teacher
    path('panel/Teacher/',TeacherListView.as_view(),name='Teacher_view'),
    path('panel/Teacher/new/', TeacherCreateView.as_view(), name='Teacher_create'),
    path('panel/Teacher/<int:pk>/', TeacherDetailView.as_view(), name='Teacher_detail'),
    path('panel/Teacher/<int:pk>/edit/', TeacherUpdateView.as_view(), name='Teacher_update'), 
    path('panel/Teacher/<int:pk>/delete/', TeacherDeleteView.as_view(), name='Teacher_delete'),

    #stock
    path('panel/stock/',StockListView.as_view(),name='stock_view'),
    path('panel/stock/new/', StockCreateView.as_view(), name='stock_create'),
    path('panel/stock/<int:pk>/', StockDetailView.as_view(), name='stock_detail'),
    path('panel/stock/<int:pk>/edit/', StockUpdateView.as_view(), name='stock_update'), 
    path('panel/stock/<int:pk>/delete/', StockDeleteView.as_view(), name='stock_delete'),
    

    path('ComingSoon/', TemplateView.as_view(template_name='ComingSoon.html'),name='ComingSoon'),
    path('Album/', TemplateView.as_view(template_name='album.html'),name='album'),
    path('store/', include('store.urls')),
     path('', include('accounts.urls')),
    path('cart/', include('carts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category
from teacher.models import Teacher

# Create your models here.

class Product(models.Model):
    product_name = models.CharField((" نام محصول "),max_length=2000, unique=True)
    slug = models.SlugField(max_length=2000, unique=True)
    description = models.IntegerField((" مدت زمان دوره"), blank=True, help_text=" ساعت ")
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    date = models.TextField((" تاریخ دوره "),max_length=200,blank=True)
    reg_date = models.TextField((" مهلت ثبت نام "),max_length=200,blank=True)
    full_description = models.TextField((" توضیحات "),max_length=20000, blank=True)
    price = models.IntegerField((" قیمت "),help_text=" تومان ")
    images = models.ImageField((" تصویر "),upload_to='photos/product')
    stock = models.IntegerField((" ظرفیت "))
    is_available = models.BooleanField((" فعال "),default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField((" تاریخ ایجاد "),auto_now_add=True)
    modified_date = models.DateTimeField((" تاریخ آخرین تغیر "),auto_now=True)
    

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class StockProduct(models.Model):
        name = models.ForeignKey(Product, on_delete=models.CASCADE)
        Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
        quantity = models.PositiveIntegerField((" ظرفیت "),default=20) 

        def __str__(self):
          return f'{self.name} {self.Teacher}'

templates/panel/stock/stock_create.html
{% extends 'baseadmin.html' %}
{% load static %}

{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>
</head>

<br><br>
<div class="update-view-container">
  <h2 class="update-title">ایجاد کلاس جدید</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'stock_view' %}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-submit">ثبت</button>
    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/stock/stock_delete.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>

</head>

<br><br>
<div class="update-view-container">
  <h2 class="update-title">حذف {{ stockproduct.name }}</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <p>آیا می خواهید کلاس با مشخصات زیر را حذف کنید؟  </p><br>
    <strong>"{{ stockproduct.name }}"</strong>
    <strong>"{{ stockproduct.Teacher }}"</strong>
    <strong>"{{ stockproduct.quantity }}"</strong>
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'stock_view' %}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-delete">حذف</button>
    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/stock/stock_update.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}

<head>
    <title>Panel</title>
    <style>
      .update-view-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
      }
      
      .update-title {
        font-size: 24px;
        margin-bottom: 30px;
      }
      
      .update-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 30px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px #007bff;
      }
      
      form input[type="text"],input[type="number"],input[type="file"],select, form textarea {
        margin-bottom: 20px;
        padding: 10px;
        border: none;
        border-radius: 5px;
        box-shadow: inset 0 0 5px #007bff;
      }
      
      form input[type="text"]:focus,input[type="number"]:focus, form textarea:focus {
        outline: none;
        box-shadow: 0 0 3px #007bff;
      }
      
      .update-buttons {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
      }
      
      .update-btn {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        color: #fff;
        transition: background-color 0.3s ease;
        width: 100px;
        height: 40px;
        text-align: center;
      }
      
      .update-btn-submit {
        background-color: rgba(0, 123, 255, 0.8);
      }
    
      .update-btn-delete {
        background-color: rgba(215, 58, 58, 0.8);
      }
      
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 20px;
      }
      
      .update-btn-submit:hover {
        background-color: #007bff;
      }
    
      .update-btn-delete:hover {
        background-color: #ee1a1a;
      }
    
      .update-btn-cancel:hover {
        background-color: #595e63;
      }
      
      .update-btn-submit:focus {
        outline: none;
        background-color: rgba(0,123, 255, 0.9);
      }
    
      .update-btn-cancel:focus {
        outline: none;
        background-color: rgba(55, 57, 59, 0.9);
    }
    
    /* media queries for smaller screen sizes */
    @media (max-width: 768px) {
      .update-view-container {
        margin-top: 30px;
      }
    
      .update-form {
        width: 100%;
      }
    
      .update-title {
        font-size: 20px;
      }
    
      .update-btn {
        padding: 8px 16px;
        font-size: 14px;
      }
    
      .update-btn-submit {
        background-color: #007bff;
      }
    
      .update-btn-cancel {
        background-color: #6c757d;
        margin-left: 10px;
      }
    }
    </style>

</head>

<br><br>
<div class="update-view-container">
  <h2 class="update-title">ویرایش {{ stockproduct.name }}</h2>
  <form method="post" class="update-form">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="update-buttons">
      <a class="update-btn update-btn-cancel" href="{% url 'stock_view' %}">انصراف</a>
      <p>&nbsp;&nbsp;&nbsp; </p>
      <button type="submit" class="update-btn update-btn-submit">ویرایش</button>

    </div>
  </form>
</div>
<br><br>
{% endblock %}

templates/panel/stock/stock_view.html
{% extends 'baseadmin.html' %}
{% load static %}
{% block content %}
<head>
    <title>Panel</title>
    <style>
        .title{
            font-family:yekan !important;
            font-size: 30px;
        }
        
        .box-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            margin: 0 -2px;
          }
          
          .list-item {
            width: 300px;
            margin: 20px 2px;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #d9d9d9;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
            border-radius: 6px;
            text-align: center;
            transition: box-shadow 0.3s ease;
          }
          
          .list-item:hover {
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
          }
          
          .list-title {
            font-size: 20px;
            font-weight: bold;
            margin: 10px 0;
          }
        
          .list-title2 {
            font-size: 15px;
            font-weight: bold;
            margin: 10px 0;
          }
          
          .list-buttons {
            margin-top: 10px;
          }
          
          .button-edit, .button-delete ,.button-new {
            width: 80px;
            margin: 0 4px;
            padding: 8px 16px;
            border-radius: 4px;
            background-color: #2196F3;
            color: #fff;
            font-weight: bold;
            text-transform: uppercase;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
            text-align: center;
          }
          
          .button-delete {
            background-color: #F44336;
          }
          
          .button-edit:hover {
            background-color: #0c7cd5;
          }
        
          .button-new {
            background-color: #998a89;
          }
          
          .button-new:hover {
            background-color: #868788;
          }
        
          .button-delete:hover {
            background-color: #b80a0a;
          }
          
          .box-container:before,
          .box-container:after {
            content: '';
            display: table;
          }
          
          .box-container:after {
            clear: both;
          }
          
          .list-item:before,
          .list-item:after {
            content: '';
            display: table;
          }
          
          .list-item:after {
            clear: both;
          }
          .dena{
            text-decoration:none;
            display: block;
              width: 40%;
              height: 40px;
              background-color:#EF4056 ;
              text-align: center;
              border-radius: 8px;
              color: whitesmoke;
              margin-top: 20px;
              margin-bottom: 20px;
              font-family: yekan;
              font-size: 20px;
              transition: 300ms;
          }
          .dena:hover{
              color: #2b2b2b;
              background-color:#e8102d ;
          }
    </style>
</head>
<div align="center">
    <a href="{% url 'stock_create' %}" class="dena"> اضافه کردن ظرفیت جدید</a>
    <a href="{% url 'panel' %}" class="dena"> صفحه اصلی پنل</a>
    <a href="{% url 'home' %}" class="dena">خروج از پنل</a>
    
    
</div>

<br><br>
<p style="text-align:center" class="title">ظرفیت - ادمین پنل</p>
<br>


<div class="box-container">
    {% comment %} <p class="branch">نام اساتید و ظرفیت دروس <p> {% endcomment %}
    {% for stockproduct in stockproduct_list %}
        {% comment %} {% if inventoryproduct.inventory.name == 'Tehran branch' %} {% endcomment %}

        <div class="list-item">
            <div class="list-title">{{ stockproduct.name }}</div><hr>
    
                <div class="list-title2"><span style="color:blue;">مدرس : </span>{{ stockproduct.Teacher}}</div>
    
                <div class="list-title2"><span style="color:blue;"> ظرفیت : </span>{{ stockproduct.quantity }}</div>

        <div class="list-buttons">
            <a href="{% url 'stock_update' stockproduct.pk %}"><button class="button-edit">ویرایش</button></a>
            <a href="{% url 'stock_delete' stockproduct.pk %}"><button class="button-delete">حذف</button></a>
        </div>
    </div>
        {% comment %} {% endif %} {% endcomment %}
    {% endfor %}
</div>
    <hr>

<br><br>
{% endblock %}